version: '3.8'

services:
  postgres:
    image: postgres:16.0
    container_name: postgres_16.0
    restart: always
    ports:
      - "15432:5432"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root