version: '3.8'

volumes:
  data-mysql:

services:
  mysql:
    image: mysql:8.0.33
    container_name: mysql_8.0.33
    restart: always
    ports:
      - "13306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - data-mysql:/var/lib/mysql
      - ./logs:/logs