version: '3.8'

services:
  redis:
    image: redis:7.2.1
    container_name: redis_7.2.1
    command: /bin/sh -c "redis-server --requirepass p@123456"
    restart: always
    ports:
      - "16379:6379"